before_install:
  - gem update --system
  - gem update bundler
before_script:
  - mkdir db
  - touch db/test.sqlite3
  - sqlite3 db/test.sqlite3 < spec/create_db.sql
cache: bundler
gemfile:
  - gemfiles/pt9_sinatra1.rb
  - gemfiles/pt9_sinatra2.rb
  - gemfiles/pt10_sinatra1.rb
  - gemfiles/pt10_sinatra2.rb
language: ruby

# For ruby compatibility, we usually only test the highest and lowest supported
# versions.
rvm:
  - 2.6.2
  - 2.3.8

script:
  - bundle exec rubocop
  - bundle exec rspec
sudo: false
